### ISSUE TITLE
请问可以删除仓库 me-cs/myspace 吗？

### ISSUE THREAD

**Issue by hitzhangjie** [me-cs/goRedisson#4]
您好，注意到你fork了一个我的个人博客的repo，这个repo本应该设置为private的，但是因为用了一个dokz的hugo模版，当时作者为了帮我定位问题顺便把权限改成public了。

因为里面可能包含一些个人见解类的信息，不便在外部公开，所以我准备把这个repo再次改成private，也希望你这边能删除。对其中的内容感兴趣的话，您可以通过地址 https://hitzhangjie.pro 来访问。

谢谢。

**Comment by me-cs** [comment]
已删除

**Comment by hitzhangjie** [comment]
❤️ 多谢
